# Generated by Django 3.0.5 on 2023-04-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_question_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='time',
        ),
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
