# Generated by Django 3.0.5 on 2023-04-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20230417_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.CharField(blank=True, default='00', max_length=100, null=True),
        ),
    ]
